services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=EduCV
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  web:
    build: ./cv_management
    command:  python cv_management/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://postgres:1234@db:5432/EduCV
    depends_on:
      - db