# Generated by Django 4.2.16 on 2024-11-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinadorAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('num_telefono', models.BigIntegerField()),
                ('universidad', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('telefono_oficina', models.BigIntegerField()),
                ('oficina', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
