# Generated by Django 4.2.16 on 2024-11-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador_academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinadoracademico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
