# Generated by Django 4.2.16 on 2024-11-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador_academico', '0002_coordinadoracademico_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinadoracademico',
            name='correo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
