# Generated by Django 4.2.16 on 2024-11-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador_academico', '0003_coordinadoracademico_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
