# Generated by Django 4.2.16 on 2024-11-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador_academico', '0005_coordinadoracademico_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinadoracademico',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='coordinadoracademico',
            name='correo',
        ),
    ]
