# Generated by Django 4.2.16 on 2024-11-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador_academico', '0007_coordinadoracademico_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='clave',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='num_telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='universidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
