# Generated by Django 4.2.16 on 2024-11-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinador_academico', '0008_alter_coordinadoracademico_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinadoracademico',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='coordinadoracademico',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='coordinadoracademico',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='coordinadoracademico',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='coordinadoracademico',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='coordinadoracademico',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='coordinadoracademico',
            name='num_telefono',
        ),
        migrations.RemoveField(
            model_name='coordinadoracademico',
            name='universidad',
        ),
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='dependencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='oficina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='telefono_oficina',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordinadoracademico',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_academico', to=settings.AUTH_USER_MODEL),
        ),
    ]
