# Generated by Django 4.2.16 on 2024-11-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador_academico', '0009_remove_coordinadoracademico_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinadoracademico',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coordinadoracademico',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coordinadoracademico',
            name='cedula',
            field=models.BigIntegerField(default='1', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinadoracademico',
            name='clave',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coordinadoracademico',
            name='correo',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinadoracademico',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coordinadoracademico',
            name='num_telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinadoracademico',
            name='universidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
