# Generated by Django 4.2.16 on 2024-11-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0003_docente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
