# Generated by Django 4.2.16 on 2024-11-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0004_privacidaddocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacidaddocente',
            name='categoria_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privacidaddocente',
            name='cedula_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privacidaddocente',
            name='contrato_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privacidaddocente',
            name='correo_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privacidaddocente',
            name='fecha_contratacion_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privacidaddocente',
            name='telefono_visible',
            field=models.BooleanField(default=True),
        ),
    ]
