# Generated by Django 4.2.16 on 2024-11-06 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docente', '0004_alter_docente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Docente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
