# Generated by Django 4.2.16 on 2024-11-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0005_alter_privacidaddocente_categoria_visible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacidaddocente',
            old_name='telefono_visible',
            new_name='num_telefono_visible',
        ),
    ]
