# Generated by Django 4.2.16 on 2024-11-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0006_remove_docente_clave_remove_docente_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='clave',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='correo',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
