# Generated by Django 4.2.16 on 2024-11-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0006_rename_telefono_visible_privacidaddocente_num_telefono_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacidaddocente',
            old_name='contrato_visible',
            new_name='tipo_contrato_visible',
        ),
    ]
