# Generated by Django 4.2.16 on 2024-12-01 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0007_rename_contrato_visible_privacidaddocente_tipo_contrato_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacidaddocente',
            name='docente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacidad', to='docente.docente'),
        ),
    ]
