# Generated by Django 4.2.16 on 2024-12-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0008_alter_privacidaddocente_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='clave',
        ),
        migrations.AlterField(
            model_name='docente',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
