# Generated by Django 4.2.16 on 2024-11-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0008_alter_docente_apellido_alter_docente_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
