# Generated by Django 4.2.16 on 2024-11-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_cv_docente'),
        ('docente', '0009_docente_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='cv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docente_cv', to='cv.cv'),
        ),
    ]
