from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='cv'),
    path('search/', search, name='search'),
    path('create/', create , name='create'),
    path('update/', update, name='update'),
    path('modifyPrivacy/', modify_privacy, name='modify_privacy'),
    path('consult/', consult , name='consult'),
    path('verify/<int:docente_id>/', verify , name='verify'),
    path('verify_personal_data/<int:docente_id>/', verify_personal_data , name='verify_personal_data'),
    path('all_teachers/', all_teachers , name='all_teachers'),
    path('teachers/', teachers , name='teachers'),
    path('update_social_links/', update_social_links , name='update_social_links'),
    path('register_experience/', register_experience , name='register_experience'),
    path('remove_experience/<int:experiencia_id>/', remove_experience , name='remove_experience'),
    path('register_academic_background/', register_academic_background, name='register_academic_background'),
    path('remove_academic_background/<int:formacion_id>/', remove_academic_background , name='remove_academic_background'),
    path('register_academic_production/', register_academic_production, name='register_academic_production'),
    path('remove_academic_production/<int:produccion_id>/', remove_academic_production , name='remove_academic_production'),
    path('register_competence/', register_competence, name='register_competence'),
    path('remove_competence/<int:competence_id>/', remove_competence , name='remove_competence'),
    path('search_teacher_main/', search_teacher_main , name='search_teacher_main'),
    path('ajax/search_teacher/', search_teacher_ajax, name='search_teacher_ajax'),
    path('teachers/', list_teachers, name='list_teachers'),
    path('consult/<int:docente_id>/', generate_curriculum , name='generate_curriculum'),
    path('docentes/resultados/', docentes_resultados, name='docentes_resultados'),
    path('get_document/', get_document, name='get_document'),
] 