# Generated by Django 4.2.16 on 2024-11-09 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv', '0001_initial'),
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='docente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_docente', to='docente.docente'),
        ),
    ]
