# Generated by Django 4.2.16 on 2024-11-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0009_docente_profile_picture'),
        ('cv', '0002_alter_experiencialaboral_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='docente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_docente', to='docente.docente'),
        ),
    ]
