# Generated by Django 4.2.16 on 2024-11-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacionacademica',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
