# Generated by Django 4.2.16 on 2024-11-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_cv_docente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormaciónAcademica',
            new_name='FormacionAcademica',
        ),
    ]
