# Generated by Django 4.2.16 on 2024-11-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_formacionacademica_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacionacademica',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='pais',
            field=models.CharField(max_length=100),
        ),
    ]
