# Generated by Django 4.2.16 on 2024-11-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_rename_formaciónacademica_formacionacademica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formacionacademica',
            old_name='fecha_obtencion',
            new_name='fecha_fin',
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='fecha_inicio',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='lugar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
