# Generated by Django 4.2.16 on 2024-11-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_formacionacademica_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccionacademica',
            old_name='fecha_realizacion',
            new_name='fecha_publicacion',
        ),
    ]
