# Generated by Django 4.2.16 on 2024-11-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_rename_fecha_obtencion_formacionacademica_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacionacademica',
            name='fecha_inicio',
        ),
    ]
