# Generated by Django 4.2.16 on 2024-11-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_remove_formacionacademica_lugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formacionacademica',
            old_name='fecha_fin',
            new_name='fecha_obtencion',
        ),
    ]
