# Generated by Django 4.2.16 on 2024-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_competencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='x',
            field=models.URLField(blank=True, null=True),
        ),
    ]
