# Generated by Django 4.2.16 on 2024-11-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_rename_fecha_fin_formacionacademica_fecha_obtencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacionacademica',
            name='fecha_obtencion',
        ),
    ]
