# Generated by Django 4.2.16 on 2024-11-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_remove_formacionacademica_fecha_obtencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fecha_fin',
        ),
    ]
