# Generated by Django 4.2.16 on 2024-11-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_remove_experiencialaboral_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
