# Generated by Django 4.2.16 on 2024-11-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_competencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='estado_verificacion',
            field=models.BooleanField(default=False),
        ),
    ]
