# Generated by Django 4.2.16 on 2024-11-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_cv_estado_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='estado_verificacion',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Verificado'), (2, 'Validado')], default=0),
        ),
    ]
