# Generated by Django 4.2.16 on 2024-12-01 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacidadCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_visible', models.BooleanField(default=True)),
                ('x_visible', models.BooleanField(default=True)),
                ('github_visible', models.BooleanField(default=True)),
                ('gmail_enviable', models.BooleanField(default=True)),
                ('outlook_enviable', models.BooleanField(default=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacidad', to='cv.cv')),
            ],
        ),
    ]
